# File @generated by Jealous/Kabelo-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See jealous/kabelo-authors.sh to make modifications.

Kabelo Mokhethi <mokhethikabelo@gmail.com>
Jealous Matsikachando <pasej5@gmail.com>
